version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: loop_api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: loop_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: schedule_visits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # TODO: We will uncomment and configure this when we create the React frontend

volumes:
  postgres_data:
